# ************************************************************
# Sequel Pro SQL dump
# Version 4096
#
# http://www.sequelpro.com/
# http://code.google.com/p/sequel-pro/
#
# Host: 127.0.0.1 (MySQL 5.6.14)
# Database: commonsdev
# Generation Time: 2014-08-05 17:29:23 +0000
# ************************************************************


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


# Dump of table wp_aha_assessment_board
# ------------------------------------------------------------

DROP TABLE IF EXISTS `wp_aha_assessment_board`;

CREATE TABLE `wp_aha_assessment_board` (
  `BOARD_ID` varchar(5) NOT NULL DEFAULT '',
  `Board_Name` varchar(57) DEFAULT NULL,
  `State` varchar(2) DEFAULT NULL,
  `State2` varchar(2) DEFAULT NULL,
  `Affiliate` varchar(17) DEFAULT NULL,
  `Nearest_MSA` varchar(80) DEFAULT NULL,
  `1.1.1.1` varchar(3) DEFAULT NULL,
  `1.1.1.2` varchar(3) DEFAULT NULL,
  `1.1.1.3` varchar(3) DEFAULT NULL,
  `1.1.1.4` varchar(12) DEFAULT NULL,
  `1.1.2.1` varchar(3) DEFAULT NULL,
  `1.1.2.2` varchar(4) DEFAULT NULL,
  `1.1.2.3` varchar(4) DEFAULT NULL,
  `1.1.2.4` varchar(3) DEFAULT NULL,
  `1.1.3.1` varchar(44) DEFAULT NULL,
  `1.2.1.1` float(4,2) DEFAULT NULL,
  `1.2.1.2` varchar(12) DEFAULT NULL,
  `1.2.2.1` float(4,2) DEFAULT NULL,
  `1.2.2.2` varchar(3) DEFAULT NULL,
  `1.2.3.1` varchar(44) DEFAULT NULL,
  `2.1.1.1` varchar(3) DEFAULT NULL,
  `2.1.1.2` varchar(2) DEFAULT NULL,
  `2.1.1.3` varchar(3) DEFAULT NULL,
  `2.1.2.1` varchar(12) DEFAULT NULL,
  `2.1.2.2` varchar(12) DEFAULT NULL,
  `2.1.2.3` varchar(12) DEFAULT NULL,
  `2.1.2.4` varchar(12) DEFAULT NULL,
  `2.1.3.1` varchar(44) DEFAULT NULL,
  `2.1.3.2` varchar(44) DEFAULT NULL,
  `2.1.4.1.1-2.1.4.1.3` varchar(10) DEFAULT NULL,
  `2.1.4.6` varchar(3) DEFAULT NULL,
  `2.2.1.1` varchar(41) DEFAULT NULL,
  `2.2.2.1` varchar(3) DEFAULT NULL,
  `2.2.2.2` varchar(255) DEFAULT NULL,
  `2.2.3.1` varchar(12) DEFAULT NULL,
  `2.2.3.2` varchar(12) DEFAULT NULL,
  `2.2.4.1` varchar(44) DEFAULT NULL,
  `2.2.5.1` varchar(10) DEFAULT NULL,
  `2.2.5.6` varchar(3) DEFAULT NULL,
  `2.3.1.1` varchar(29) DEFAULT NULL,
  `2.3.1.3` varchar(12) DEFAULT NULL,
  `2.3.2.1` varchar(3) DEFAULT NULL,
  `2.3.2.2` varchar(255) DEFAULT NULL,
  `2.3.3` varchar(255) DEFAULT NULL,
  `3.1.1.1` varchar(3) DEFAULT NULL,
  `3.1.1.1.1` varchar(6) DEFAULT NULL,
  `3.1.3.1-3.1.3.3` varchar(10) DEFAULT NULL,
  `3.1.3.6` varchar(3) DEFAULT NULL,
  `3.1.4` text,
  `3.2.1.1` varchar(10) DEFAULT NULL,
  `3.2.1.6` varchar(3) DEFAULT NULL,
  `3.2.2` varchar(3) DEFAULT NULL,
  `3.3.1.1` varchar(3) DEFAULT NULL,
  `3.3.1.2` varchar(10) DEFAULT NULL,
  `3.3.2.1` varchar(12) DEFAULT NULL,
  `3.3.2.2` varchar(12) DEFAULT NULL,
  `3.3.3.1` varchar(255) DEFAULT NULL,
  `3.3.3.2` varchar(255) DEFAULT NULL,
  `3.3.4` varchar(44) DEFAULT NULL,
  `3.4.1` varchar(54) DEFAULT NULL,
  `3.4.2` varchar(3) DEFAULT NULL,
  `3.4.3.1` varchar(12) DEFAULT NULL,
  `3.4.3.2` varchar(12) DEFAULT NULL,
  `3.4.4` varchar(44) DEFAULT NULL,
  `3.5.1` varchar(19) DEFAULT NULL,
  `3.5.2` varchar(3) DEFAULT NULL,
  `3.5.3` varchar(12) DEFAULT NULL,
  `3.5.4` varchar(44) DEFAULT NULL,
  `4.1.1` varchar(19) DEFAULT NULL,
  `4.1.2.1` varchar(3) DEFAULT NULL,
  `4.1.2.2` varchar(3) DEFAULT NULL,
  `4.1.3.1` varchar(12) DEFAULT NULL,
  `4.1.3.2` varchar(12) DEFAULT NULL,
  `4.1.4` varchar(44) DEFAULT NULL,
  `5.1.1` varchar(3) DEFAULT NULL,
  `5.1.2` varchar(12) DEFAULT NULL,
  `5.1.3` varchar(44) DEFAULT NULL,
  `5.1.4.1` varchar(10) DEFAULT NULL,
  `5.1.4.6` varchar(10) DEFAULT NULL,
  `6.1.1` varchar(3) DEFAULT NULL,
  `6.1.2` varchar(3) DEFAULT NULL,
  `6.1.3` varchar(19) DEFAULT NULL,
  PRIMARY KEY (`BOARD_ID`),
  UNIQUE KEY `BOARD_ID` (`BOARD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

LOCK TABLES `wp_aha_assessment_board` WRITE;
/*!40000 ALTER TABLE `wp_aha_assessment_board` DISABLE KEYS */;

INSERT INTO `wp_aha_assessment_board` (`BOARD_ID`, `Board_Name`, `State`, `State2`, `Affiliate`, `Nearest_MSA`, `1.1.1.1`, `1.1.1.2`, `1.1.1.3`, `1.1.1.4`, `1.1.2.1`, `1.1.2.2`, `1.1.2.3`, `1.1.2.4`, `1.1.3.1`, `1.2.1.1`, `1.2.1.2`, `1.2.2.1`, `1.2.2.2`, `1.2.3.1`, `2.1.1.1`, `2.1.1.2`, `2.1.1.3`, `2.1.2.1`, `2.1.2.2`, `2.1.2.3`, `2.1.2.4`, `2.1.3.1`, `2.1.3.2`, `2.1.4.1.1-2.1.4.1.3`, `2.1.4.6`, `2.2.1.1`, `2.2.2.1`, `2.2.2.2`, `2.2.3.1`, `2.2.3.2`, `2.2.4.1`, `2.2.5.1`, `2.2.5.6`, `2.3.1.1`, `2.3.1.3`, `2.3.2.1`, `2.3.2.2`, `2.3.3`, `3.1.1.1`, `3.1.1.1.1`, `3.1.3.1-3.1.3.3`, `3.1.3.6`, `3.1.4`, `3.2.1.1`, `3.2.1.6`, `3.2.2`, `3.3.1.1`, `3.3.1.2`, `3.3.2.1`, `3.3.2.2`, `3.3.3.1`, `3.3.3.2`, `3.3.4`, `3.4.1`, `3.4.2`, `3.4.3.1`, `3.4.3.2`, `3.4.4`, `3.5.1`, `3.5.2`, `3.5.3`, `3.5.4`, `4.1.1`, `4.1.2.1`, `4.1.2.2`, `4.1.3.1`, `4.1.3.2`, `4.1.4`, `5.1.1`, `5.1.2`, `5.1.3`, `5.1.4.1`, `5.1.4.6`, `6.1.1`, `6.1.2`, `6.1.3`)
VALUES
	('FDA01','Albany (NY)','NY','','Founders','Albany-Schenectady-Troy, NY Metropolitan Statistical Area','Yes','Yes','Yes','FY 2016-2017','No','100','50','75','Not a viable issue at any level at this time',1.55,'FY 2016-2017',0.38,'','Not a viable issue at any level at this time','','','','FY 2016-2017','FY 2016-2017','FY 2016-2017','FY 2016-2017','At the state and local level','At the state and local level','','60','Clarifying that users are liable','1','You know what I mean, right?','FY 2016-2017','FY 2016-2017','neither','','','No ','FY 2016-2017','1','Dr Samabee','local','','Low','','','a:3:{s:10:\"strengthen\";s:1:\"1\";s:12:\"celebrations\";s:1:\"1\";s:3:\"tbd\";s:1:\"1\";}','','','0','','','FY 2016-2017','FY 2016-2017','yes - below AHA standards','Schenechtady','state and local','No','','FY 2016-2017','FY 2016-2017','At the state and local level','','0','FY 2016-2017','local','','','','FY 2016-2017','FY 2016-2017','Not a viable issue at any level at this time','0','FY 2016-2017','At the state and local level','','','','',''),
	('FDA02','Buffalo Niagara Region (NY)','NY','','Founders','Buffalo-Niagara Falls, NY Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA04','Dutchess-Ulster Counties (NY)','NY','','Founders','Poughkeepsie-Newburgh-Middletown, NY Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA05','Greater Boston (MA)','MA','','Founders','Boston-Cambridge-Quincy, MA-NH Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA06','Greater Hartford (CT)','CT','','Founders','Hartford-West Hartford-East Hartford, CT Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA07','Long Island (NY)','NY','','Founders','New York-Northern New Jersey-Long Island, NY-NJ-PA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA08','Maine (ME)','ME','','Founders','Portland-South Portland-Biddeford, ME Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA09','New Hampshire  (NH)','NH','','Founders','Boston-Cambridge-Quincy, MA-NH Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA10','New York (NY)','NY','','Founders','New York-Northern New Jersey-Long Island, NY-NJ-PA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','1','Shared use policy descriptions rock so hard.','','','state and local','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA11','Northern New Jersey (NJ)','NJ','','Founders','New York-Northern New Jersey-Long Island, NY-NJ-PA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA12','Orange-Sullivan-Rockland Counties (Tri County Board) (NY)','NY','','Founders','Poughkeepsie-Newburgh-Middletown, NY Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA13','Rhode Island (RI)','RI','','Founders','Providence-New Bedford-Fall River, RI-MA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA14','Rochester (NY)','NY','','Founders','Rochester, NY Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA15','Syracuse (NY)','NY','','Founders','Syracuse, NY Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA16','Utica (NY)','NY','','Founders','Utica-Rome, NY Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA17','Vermont (VT)','VT','','Founders','Burlington-South Burlington, VT Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA18','Southern NJ (NJ)','NJ','','Founders','Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('FDA19','Central NJ (NJ)','NJ','','Founders','New York-Northern New Jersey-Long Island, NY-NJ-PA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA01','Adams (PA)','PA','','Great Rivers','Gettysburg, PA Micropolitan Statistical Area','No','No','Yes','FY 2014-2015','Yes','100%','100%','50%','At the state level',NULL,'FY 2014-2015',NULL,'Yes','At the state level','Yes','No','Yes','FY 2014-2015','FY 2014-2015','FY 2014-2015','FY 2014-2015','At the state level','At the state level','','50%','Liability protection from injury','1','Describing state promotion things.  at the local level.','FY 2014-2015','FY 2014-2015','local','','60%','Yes, meets our guidelines','FY 2014-2015','Yes','Open text','At the state level','Yes','High','','60%','Yes ? Publish / strengthen the district wellness policy','','60%','Yes','Yes','','FY 2014-2015','FY 2014-2015','Yes, vending and/or service policies that meet or exceed AHA standards.','Open text','At the state level','Yes, proposed policies meet our guidelines.','Yes','FY 2014-2015','FY 2014-2015','At the state level','50%','Yes','FY 2014-2015','At the state level','[Data from Commons]','Yes','Yes','FY 2014-2015','FY 2014-2015','Yes ? Medicaid expansion at the state level','Yes','FY 2014-2015','At the state level','','','50%','50%','[See Hospitals tab]'),
	('GRA02','Akron (OH)','OH','','Great Rivers','Akron, OH Metropolitan Statistical Area','Yes','Yes','Yes','FY 2015-2016','No','','','','At the local level',NULL,'FY 2015-2016',NULL,'No','At the local level','','','','FY 2015-2016','FY 2015-2016','FY 2015-2016','FY 2015-2016','At the local level','At the local level','','','Liability protection from property damage','1','Some moar text....not sure how big we should make this in the database.....','FY 2015-2016','FY 2015-2016','state and local','','','Yes, but below our guidelines','FY 2015-2016','No','Open text','At the local level','No','Medium','','','Yes ? Open a door for the Alliance for a Healthier Generation','','','No','No','','FY 2015-2016','FY 2015-2016','Yes, vending and/or service policies but below AHA standards.? ','','At the local level','Yes, but proposed policies do not meet our guidelines.','No','FY 2015-2016','FY 2015-2016','At the local level','[Data from Commons]','No','FY 2015-2016','At the local level','','No','No','FY 2015-2016','FY 2015-2016','Yes ? USPSTF at the state level','No','FY 2015-2016','At the local level','','','','',''),
	('GRA03','Allegheny (PA)','PA','','Great Rivers','Pittsburgh, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','No ? none of the above','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA04','Beaver Butler Counties Board (PA)','PA','','Great Rivers','Pittsburgh, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA05','Canton (OH)','OH','','Great Rivers','Canton-Massillon, OH Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA06','Capital Region (PA)','PA','','Great Rivers','Harrisburg-Carlisle, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA07','Charleston (WV)','WV','','Great Rivers','Charleston, WV Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA08','Cincinnati (OH)','OH','','Great Rivers','Cincinnati-Middletown, OH-KY-IN Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA09','Cleveland (OH)','OH','','Great Rivers','Cleveland-Elyria-Mentor, OH Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA10','Columbus (OH)','OH','','Great Rivers','Columbus, OH Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA11','Dayton (OH)','OH','','Great Rivers','Dayton, OH Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA12','Erie (PA)','PA','','Great Rivers','Erie, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA13','Franklin Fulton (PA)','PA','','Great Rivers','Chambersburg, PA Micropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA14','Lancaster (PA)','PA','','Great Rivers','Lancaster, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA15','Lebanon (PA)','PA','','Great Rivers','Lebanon, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA16','Lehigh Valley (PA)','PA','','Great Rivers','Reading, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA17','Lexington (KY)','KY','','Great Rivers','Lexington-Fayette, KY Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA18','Louisville (KY)','KY','','Great Rivers','Louisville-Jefferson County, KY-IN Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA19','Middletown (OH)','OH','','Great Rivers','Cincinnati-Middletown, OH-KY-IN Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA20','New Castle (DE)','DE','','Great Rivers','Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA21','Northeast PA (PA)','PA','','Great Rivers','Scranton--Wilkes-Barre, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA22','Philadelphia (PA)','PA','','Great Rivers','Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','1','yeps','','','state and local','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA23','Southern Delaware (DE)','DE','','Great Rivers','Seaford, DE Micropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA24','Washington County and Mon Valley Board (PA)','PA','','Great Rivers','Pittsburgh, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA25','Westmoreland County Board (PA)','PA','','Great Rivers','Pittsburgh, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA26','York (PA)','PA','','Great Rivers','York-Hanover, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA27','Youngstown (OH)','OH','PA','Great Rivers','Youngstown-Warren-Boardman, OH-PA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA28','Toledo (OH)','OH','','Great Rivers','Toledo, OH Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GRA29','Fayette (PA)','PA','','Great Rivers','Pittsburgh, PA Metropolitan Statistical Area','No','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA01','Atlanta (GA)','GA','','Greater Southeast','Atlanta-Sandy Springs-Marietta, GA Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','TBD ? more info needed','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA02','Baton Rouge (LA)','LA','','Greater Southeast','Baton Rouge, LA Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA03','Birmingham (AL)','AL','','Greater Southeast','Birmingham-Hoover, AL Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA04','Greater New Orleans Area (LA)','LA','','Greater Southeast','New Orleans-Metairie-Kenner, LA Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA05','Jacksonville (FL)','FL','','Greater Southeast','Jacksonville, FL Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA06','Memphis (TN)','TN','','Greater Southeast','Memphis, TN-MS-AR Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA07','Miami / Ft. Lauderdale (FL)','FL','','Greater Southeast','Miami-Fort Lauderdale-Pompano Beach, FL Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA08','Nashville (TN)','TN','','Greater Southeast','Nashville-Davidson--Murfreesboro--Franklin, TN Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA09','Orlando (FL)','FL','','Greater Southeast','Orlando-Kissimmee-Sanford, FL Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA10','Palm Beach (FL)','FL','','Greater Southeast','Miami-Fort Lauderdale-Pompano Beach, FL Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA11','Southwest Florida (FL)','FL','','Greater Southeast','Cape Coral-Fort Myers, FL Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA12','Tampa Bay (FL)','FL','','Greater Southeast','Tampa-St. Petersburg-Clearwater, FL Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA13','Rutherford County (TN)','TN','','Greater Southeast','Nashville-Davidson--Murfreesboro--Franklin, TN Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('GSA14','Jackson (MS)','MS','','Greater Southeast','Jackson, MS Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MAA01','Charlotte (NC)','NC','','Mid-Atlantic','Charlotte-Gastonia-Rock Hill, NC-SC Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MAA02','Greater Baltimore (MD)','MD','','Mid-Atlantic','Baltimore-Towson, MD Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MAA03','Greater Washington Region (DC)','DC','','Mid-Atlantic','Washington-Arlington-Alexandria, DC-VA-MD-WV Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MAA04','Hampton Roads (VA)','VA','','Mid-Atlantic','Virginia Beach-Norfolk-Newport News, VA-NC Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MAA05','Richmond (VA)','VA','','Mid-Atlantic','Richmond, VA Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MAA06','Triangle Metro Division (NC)','NC','','Mid-Atlantic','Raleigh-Cary, NC Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MAA07','Columbia (SC)','SC','','Mid-Atlantic','Columbia, SC Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA01','Chicago (IL)','IL','','Midwest','Chicago-Joliet-Naperville, IL-IN-WI Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA02','Des Moines (IA)','IA','','Midwest','Des Moines-West Des Moines, IA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA03','Detroit (MI)','MI','','Midwest','Detroit-Warren-Livonia, MI Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA04','Indianapolis (IN)','IN','','Midwest','Indianapolis-Carmel, IN Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA05','Kansas City (MO)','MO','KS','Midwest','Kansas City, MO-KS Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA06','Milwaukee (WI)','WI','','Midwest','Milwaukee-Waukesha-West Allis, WI Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA07','Omaha (NE)','NE','','Midwest','Omaha-Council Bluffs, NE-IA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA08','St Louis (MO)','MO','IL','Midwest','St. Louis, MO-IL Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA09','Twin Cities (MN)','MN','','Midwest','Minneapolis-St. Paul-Bloomington, MN-WI Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA10','Wichita (KS)','KS','','Midwest','Wichita, KS Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA11','Madison (WI)','WI','','Midwest','Madison, WI Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA12','Grand Rapid (MI)','MI','','Midwest','Grand Rapids-Wyoming, MI Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('MWA13','NW Indiana  (IN)','IN','','Midwest','Chicago-Joliet-Naperville, IL-IN-WI Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA01','Albuquerque (NM)','NM','','SouthWest','Albuquerque, NM Metropolitan Statistical Area','Yes','Yes','No','No','','','','','',NULL,'No',NULL,'','','','','','No','No','No','No','Not a viable issue at any level at this time','Not a viable issue at any level at this time','','','None of the above ','','','No','No','Not a viable issue at any level at this time','','','','No','','','Not a viable issue at any level at this time','','','','','Yes ? Strengthen competitive foods policy by addressing celebrations and fundraisers','','','','','','No','No','','','Not a viable issue at any level at this time','','','No','No','Not a viable issue at any level at this time','','','No','Not a viable issue at any level at this time','','','','No','No','','','','Not a viable issue at any level at this time','','','','',''),
	('SWA02','Austin (TX)','TX','','SouthWest','Austin-Round Rock-San Marcos, TX Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA03','Colorado Springs (CO)','CO','','SouthWest','Colorado Springs, CO Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA04','Corpus Christi (TX)','TX','','SouthWest','Corpus Christi, TX Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA05','Dallas (TX)','TX','','SouthWest','Dallas-Fort Worth-Arlington, TX Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA06','Denver (CO)','CO','','SouthWest','Denver-Aurora-Broomfield, CO Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA07','Houston (TX)','TX','','SouthWest','Houston-Sugar Land-Baytown, TX Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA08','Little Rock (AR)','AR','','SouthWest','Little Rock-North Little Rock-Conway, AR Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA09','Northwest Arkansas (AR)','AR','','SouthWest','Fayetteville-Springdale-Rogers, AR-MO Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA10','Oklahoma City (OK)','OK','','SouthWest','Oklahoma City, OK Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA11','San Antonio (TX)','TX','','SouthWest','San Antonio-New Braunfels, TX Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA12','Tarrant County (TX)','TX','','SouthWest','Dallas-Fort Worth-Arlington, TX Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA13','Tulsa (OK)','OK','','SouthWest','Tulsa, OK Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('SWA14','Montgomery County (TX)','TX','','SouthWest','Houston-Sugar Land-Baytown, TX Metropolitan Statistical Area','No','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA01','Boise (ID)','ID','','Western States','Boise City-Nampa, ID Metropolitan Statistical Area','Yes','No','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA02','Central Coast Division (CA)','CA','','Western States','Santa Barbara-Santa Maria-Goleta, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA03','Central Valley Division (CA)','CA','','Western States','Fresno, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA04','Coachella Valley Division (CA)','CA','','Western States','Riverside-San Bernardino-Ontario, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA05','East Bay Division (CA)','CA','','Western States','San Francisco-Oakland-Fremont, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA06','Hawaii (HI)','HI','','Western States','Honolulu, HI Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA07','Inland Empire Division (CA)','CA','','Western States','Riverside-San Bernardino-Ontario, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA08','Kern County Division (CA)','CA','','Western States','Bakersfield-Delano, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA09','Las Vegas Division (NV)','NV','','Western States','Las Vegas-Paradise, NV Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA10','Los Angeles County Division (CA)','CA','','Western States','Los Angeles-Long Beach-Santa Ana, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA11','Northern Nevada (NV)','NV','','Western States','Reno-Sparks, NV Metropolitan Statistical Area','Yes','No','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA12','Portland (OR)','OR','','Western States','Portland-Vancouver-Hillsboro, OR-WA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA13','Orange County Division (CA)','CA','','Western States','Los Angeles-Long Beach-Santa Ana, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA14','Phoenix (AZ)','AZ','','Western States','Phoenix-Mesa-Glendale, AZ Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA15','Sacramento Division (CA)','CA','','Western States','Sacramento--Arden-Arcade--Roseville, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA16','San Diego Division (CA)','CA','','Western States','San Diego-Carlsbad-San Marcos, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA17','San Francisco Division (CA)','CA','','Western States','San Francisco-Oakland-Fremont, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA18','Seattle (WA)','WA','','Western States','Seattle-Tacoma-Bellevue, WA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA19','Silicon Valley (CA)','CA','','Western States','San Jose-Sunnyvale-Santa Clara, CA Metropolitan Statistical Area','Yes','Yes','No','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA20','Tacoma (WA)','WA','','Western States','Seattle-Tacoma-Bellevue, WA Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA21','Tucson (AZ)','AZ','','Western States','Tucson, AZ Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','',''),
	('WSA22','Utah Division (UT)','UT','','Western States','Salt Lake City, UT Metropolitan Statistical Area','Yes','Yes','Yes','','','','','','',NULL,'',NULL,'','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','','');

/*!40000 ALTER TABLE `wp_aha_assessment_board` ENABLE KEYS */;
UNLOCK TABLES;



/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
